modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="observerlib.mixins.json"
[[mods]]
modId="observerlib"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://minecraft.curseforge.com/projects/observerlib"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''${mod_description}'''
[[dependencies.observerlib]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.observerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.4)"
    ordering="NONE"
    side="BOTH"