modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/HellFirePvP/ObserverLib/issues"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="observerlib.mixins.json"
[[mods]]
modId="observerlib"
version="${mod_version}"
displayName="ObserverLib"
displayURL="https://minecraft.curseforge.com/projects/observerlib"
logoFile="logo.png"
authors="HellFirePvP"
displayTest="MATCH_VERSION"
description='''Cached world structure and change monitoring library.'''
[[dependencies.observerlib]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.observerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.4)"
    ordering="NONE"
    side="BOTH"