modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/HellFirePvP/ObserverLib/issues"
[[mods]] #mandatory
modId="observerlib"
version="${file.jarVersion}"
displayName="ObserverLib"
displayURL="https://minecraft.curseforge.com/projects/observerlib"
logoFile="logo.png"
authors="HellFirePvP"
description='''Cached world structure and change monitoring library.'''
[[dependencies.observerlib]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.observerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"